name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: Push to Azure Storage
      uses: tibor19/static-website-deploy@v1
      with:
        # Connection String of the Azure Storage Container
        connection-string: ${{ secret.STORAGE_CONNECTION_STRING }}
        # Folder containing the files to be uploaded to the Storage Container
        folder: .
        # Name of the Blob Container Storage
        blob-container-name: $web
        # Access Policy to update in the Container (BlobContainer | Blob | None). For private containers do not specity any value.
        public-access-policy:
        # Enabled static website
        enabled-static-website: true
        # Index file for the static website
        index-file: 'index.html'
        # 404 Error file for the static website
        error-file:
        # If the existing files should be removed before uploading the new files
        remove-existing-files: true